# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0803b78d38fb35b539ded4014c215bd5057581750fcb92103a7ef6608379bf3301ad7ae9c6b804f1a588db746c5de08a9a4c832014cd76afd01fbb17be4c9c6

test:
  secret_key_base: 61434c0bd09fe739cbd08aa7fb89adcba0fb697065c84ec66237fd4f3339839e682db7e196699237d965b2a2a744611e5ac8aea747be22d810ad2f4e21672220

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
